### PR TITLE
Add support for VectorDrawable in BasicWelcomeFragment

### PR DESCRIPTION
**Pull request by mehmetakiftutuncu**
I use `VectorDrawable`s in my project and I noticed they caused issues below Android 5. I looked around found this solution. I am currently using my modified version in my project. If you could merge this (and possibly apply the same logic to your entire project), I'll switch to using your project as an external dependency.

Thanks.

### CODE REVIEW

**Comment by stephentuso** [comment]
That travis build failed because I hadn't updated the gradle plugin version in a while, which I just did. Try moving the change from `BasicWelcomeFragment` into `WelcomeActivity`, just put it after `setContentView`. From the brief amount of searching I did, I think if you put that in the activity, it will apply to all the fragments. If that doesn't work, let me know and I'll just merge this.

**Comment by mehmetakiftutuncu** [comment]
Sure, I'll look into it when I'm on my computer. Thanks. :)

**Comment by stephentuso** [comment]
@mehmetakiftutuncu I've gotten more familiar with vector drawables over the past week. You're using drawables similar to [this](https://github.com/stephentuso/welcome-android/blob/master/sample/src/main/res/drawable/ic_image_white.xml), right? Here are some quotes from the [reference](https://developer.android.com/reference/android/support/v7/app/AppCompatDelegate.html#setCompatVectorFromResourcesEnabled(boolean)) for `setCompatVectorFromResourcesEnabled`:

> This feature defaults to disabled, since enabling it can cause issues with memory usage, and problems updating Configuration instances.

> Even with this disabled, you can still use vector resources through `setImageResource(int)` and it's `app:srcCompat` attribute.

> Please note: this only takes effect in Activities created after this call.

The fragments included in the library all use `setImageResource`, and for custom fragments you could just use the `app:srcCompat` attribute. Also, if you do need to call it, since it takes effect in activities created after the call, it would make more sense to put it in the launcher activity or `Application` class. For these reasons, and also since it says it can cause issues with memory usage, I think that call should be removed from `WelcomeActivity`. 

It also seems that putting `vectorDrawables.useSupportLibrary = true` in the library's `build.gradle` had no effect, it is only needed in the app. 

Could you try using version 0.7.2 of the library, and just adding  `vectorDrawables.useSupportLibrary = true` in your app's `build.gradle`? That is working for me in the sample app, let me know if it works for you and I'll make those changes, thanks

**Comment by mehmetakiftutuncu** [comment]
Hi again,

I'm using this library in my app [Muezzin](https://github.com/mehmetakiftutuncu/Muezzin) and it seems to be working fine. However, I had to use my own version of the library for the latest version of my app because this PR hadn't been merged yet.

I didn't have much time to do extensive testing with lower API levels but the idea is the same to support vector drawables. So, I think it should work. :)

Also, you're right about `vectorDrawables.useSupportLibrary = true` part. This is needed for the application, not the library. :)

When I get more time, I'll update my app to use your library with you binaries again and test more.

Thanks.

**Comment by stephentuso** [comment]
I actually did merge it, your changes are included in version 0.7.3. However, I'm going to go ahead and remove the `AppCompatDelegate` call, as it doesn't have any effect. It shouldn't affect your app, but if it does I can make any changes that are needed once you get a chance to test it

**Comment by mehmetakiftutuncu** [comment]
I meant it hadn't been merged when I was publishing my app, therefore I used the library as a module with my modifications. :) I'll let you know if anything breaks and we can test more. 👍

**Pull request merged**
